#include    <stdio.h>
#include    <stdlib.h>
#include    <string.h>
#include    "hal_data.h"

#define BL  0x08    // Back Light
#define EN  0x04    // Emable
#define RW  0x02    // Read/Write
#define DT  0x01    // Regista Select / Data
#define CM  0x00    // Regista Select / Command

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

void ToggleLED1(void);
void ToggleLED2(void);
void SendUart(char* str);
void RecvUart(char *buff, int i);
void UartaCallback(uart_callback_args_t *p_args);
void TimerCallback(timer_callback_args_t *p_args);
void delay(int ms);
void IicaCallback(i2c_master_callback_args_t *p_args);
void WriteIIC(int data);
void SendIIC(int rs, int data);
void InitLCD(void);
void ClearLCD(void);
void WriteLCD(int x, int y, char* data);
void SetTime(void);
void DispTime(void);

static volatile bool uart_sending   = false;
static volatile bool uart_receiving = false;
static volatile bool timer_wait     = false;
static volatile bool i2c_writing    = false;
static volatile bool rtc_irq       = false;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    int         i = 0;
    char        buff[80];
    char        temp[80];

    R_TAU_Open(&g_timer0_ctrl, &g_timer0_cfg);
    R_UARTA_Open(&g_uart0_ctrl, &g_uart0_cfg);
    R_IICA_MASTER_Open(&g_iica_master0_ctrl, &g_iica_master0_cfg);
    R_RTC_C_Open(&g_rtc0_ctrl, &g_rtc0_cfg);

    while (100 - i++) {
        sprintf(buff, "%s%s%s ",
                i%3? "": "Fizz",
                i%5? "": "Buzz",
                i%3&&i%5? __itoa(i, temp, 10): ""
        );
        SendUart(buff);

//        delay(10);
        ToggleLED1();
        ToggleLED2();
    }
    SendUart("\n");

    InitLCD();
    WriteLCD(0, 0, "Hello RA0E1");

    SetTime();

    while (1) {
        if (rtc_irq) {
            rtc_irq = false;
            DispTime();
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
void ToggleLED1(void)
{
    bsp_io_level_t  value;

    R_IOPORT_PinRead(&g_ioport_ctrl, LED1, &value);
    R_IOPORT_PinWrite(&g_ioport_ctrl, LED1, !value);
}

void ToggleLED2(void)
{
    bsp_io_level_t  value;

    R_IOPORT_PinRead(&g_ioport_ctrl, LED2, &value);
    R_IOPORT_PinWrite(&g_ioport_ctrl, LED2, !value);
}

void SendUart(char* str)
{
    uart_sending = true;
    R_UARTA_Write(&g_uart0_ctrl, (uint8_t*)str, strlen(str));
    while (uart_sending) ;
}

void RecvUart(char *buff, int i)
{
    uart_receiving = true;
    R_UARTA_Read(&g_uart0_ctrl, (uint8_t*)buff, (uint32_t)i);
    while (uart_receiving) ;
    uart_receiving = false;
}

/* Callback function */
void UartaCallback(uart_callback_args_t *p_args)
{
    switch ((char)p_args->event) {
        case UART_EVENT_TX_COMPLETE:
            uart_sending = false;
            break;
        case UART_EVENT_RX_COMPLETE:
            uart_receiving = false;
            break;
    }
}
/* Callback function */
void TimerCallback(timer_callback_args_t *p_args)
{
    if (p_args->event == TIMER_EVENT_CYCLE_END) {
        timer_wait = false;
    }
}

void delay(int ms)
{
    int     i;

    R_TAU_Start(&g_timer0_ctrl);
    for (i = 0; i < ms; i++) {
        timer_wait = true;
        while (timer_wait) ;
    }
    R_TAU_Stop(&g_timer0_ctrl);
}

/* Callback function */
void IicaCallback(i2c_master_callback_args_t *p_args)
{
    switch(p_args->event){
        case I2C_MASTER_EVENT_TX_COMPLETE :
            i2c_writing = false;
            break;
        default:
            break;
    }
}

void WriteIIC(int data)
{
    int     tmp;

    tmp = data;

    i2c_writing = true;
    R_IICA_MASTER_Write(&g_iica_master0_ctrl, (uint8_t*)&tmp, 1, false);
    while (i2c_writing) ;
}

void SendIIC(int rs, int data)
{
    int buf;

    // send bit7-4 firstly
    buf = data & 0xF0;
    buf |= BL | EN | rs;        // BL=1, EN=1, RW=0, RS=0
    WriteIIC(buf);
    delay(2);
    buf &= ~EN;        // EN=0
    WriteIIC(buf);
    __NOP();
    // send bit3-0 secondly
    buf = ((data & 0x0F) << 4);
    buf |= BL | EN | rs;        // BL=1, EN=1, RW=0, RS=0
    WriteIIC(buf);
    delay(2);
    buf &= ~EN;        // EN=0
    WriteIIC(buf);
    __NOP();
}

void InitLCD(void)
{
    delay(15);
    SendIIC(CM, 0x33); // 8-line mode
    delay(5);
    SendIIC(CM, 0x32); // 4-line mode
    delay(5);
    SendIIC(CM, 0x28); // 2Lines & 5*7 dots
    delay(5);
    SendIIC(CM, 0x0C); // Enable display without cursor
    delay(5);
    SendIIC(CM, 0x01); // Clear Screen
}

void ClearLCD(void)
{
    SendIIC(CM, 0x01);  // Clear Screen
}

void WriteLCD(int x, int y, char data[])
{
    volatile int     addr, i;
    volatile int     len;

    if (x < 0)  x = 0;
    if (15 < x) x = 15;
    if (y < 0)  y = 0;
    if (1 < y)  y = 1;

    addr = 0x80 + 0x40 * y + x;
    SendIIC(CM, addr);

    len = (int)strlen(data);
    for (i = 0; i < len; i++) {
        SendIIC(DT, data[i]);
    }
}

/* Callback function */
void RtcCallback(rtc_callback_args_t *p_args)
{
    if (p_args->event == RTC_EVENT_PERIODIC_IRQ) {
        rtc_irq = true;
    }
}

void SetTime(void)
{
    rtc_time_t  time;
    char        buff[80];

    sprintf(buff, "Enter time value.");
    SendUart(buff);

    sprintf(buff, "\n     Year > ");
    SendUart(buff);
    RecvUart(buff, 4);
    time.tm_year = atoi(buff) - 1900;

    sprintf(buff, "\n     Month > ");
    SendUart(buff);
    RecvUart(buff, 2);
    time.tm_mon = atoi(buff) - 1;

    sprintf(buff, "\n     Day > ");
    SendUart(buff);
    RecvUart(buff, 2);
    time.tm_mday = atoi(buff);

    sprintf(buff, "\n     Hour > ");
    SendUart(buff);
    RecvUart(buff, 2);
    time.tm_hour = atoi(buff);

    sprintf(buff, "\n     Min > ");
    SendUart(buff);
    RecvUart(buff, 2);
    time.tm_min = atoi(buff);

    sprintf(buff, "\n     Sec > ");
    SendUart(buff);
    RecvUart(buff, 2);
    time.tm_sec = atoi(buff);

    sprintf(buff, "\n");
    SendUart(buff);

    R_RTC_C_CalendarTimeSet(&g_rtc0_ctrl, &time);

    R_RTC_C_PeriodicIrqRateSet(&g_rtc0_ctrl, RTC_PERIODIC_IRQ_SELECT_1_SECOND);
}

void DispTime(void)
{
    int                 i;
    char                buff[80];
    rtc_time_t          ts;
    static rtc_time_t   prev;

    R_RTC_C_CalendarTimeGet(&g_rtc0_ctrl, &ts);

    // UART
    sprintf(buff, "%4d/%02d/%02d ",
                    ts.tm_year+1900, ts.tm_mon+1, ts.tm_mday
    );
    SendUart(buff);
    sprintf(buff, "%02d:%02d:%02d ",
                    ts.tm_hour, ts.tm_min, ts.tm_sec);
    SendUart(buff);
    i = ts.tm_sec;
    sprintf(buff, "%s%s%s",
            i%3? "":"Fizz", i%5? "": "Buzz", i%3&&i%5? "        ": "");
    SendUart(buff);
    SendUart("\n");

    // LCD
    if (ts.tm_year != prev.tm_year) {
        sprintf(buff, "%4d/", ts.tm_year+1900);
        WriteLCD(0, 0, buff);
    }
    if (ts.tm_mon != prev.tm_mon) {
        sprintf(buff, "%02d/", ts.tm_mon+1);
        WriteLCD(5, 0, buff);
    }
    if (ts.tm_mday != prev.tm_mday) {
        sprintf(buff, "%02d ", ts.tm_mday);
        WriteLCD(8, 0, buff);
    }
    if (ts.tm_hour != prev.tm_hour) {
        sprintf(buff, "%02d:",ts.tm_hour);
        WriteLCD(0, 1, buff);
    }
    if (ts.tm_min != prev.tm_min) {
        sprintf(buff, "%02d:",ts.tm_min);
        WriteLCD(3, 1, buff);
    }
    if (ts.tm_sec != prev.tm_sec) {
        sprintf(buff, "%02d",ts.tm_sec);
        WriteLCD(6, 1, buff);
        i = ts.tm_sec;
        sprintf(buff, "%s%s%s",
                i%3? "":"Fizz", i%5? "": "Buzz", i%3&&i%5? "        ": "");
        WriteLCD(8, 1, buff);
    }
    prev = ts;
}

void SetCGRAM(int cc, char ptn)
{

}
